//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "assets")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub symbol: String,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::orders::Entity")]
    Orders,
    #[sea_orm(has_many = "super::trades::Entity")]
    Trades,
    #[sea_orm(has_many = "super::user_balances::Entity")]
    UserBalances,
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl Related<super::trades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trades.def()
    }
}

impl Related<super::user_balances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserBalances.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
